### ISSUE TITLE
Footer styling should fix to bottom of page, not bottom of window

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-website#11]
At least one individual saw this:

https://github.com/Watts-Lab/deliberation-website/assets/4304478/639f8c4b-eccb-4e32-811f-3cd2a4b9d4ab

Styling should be so that this is not the case...

**Comment by gumillie222** [comment]
Before I changed anything the footer is at the bottom of the page for me. I've added `bottom: 0;` and `position: static;` to the footer css, but not sure it would solve this issue. I can't really check... I can look into it more if still not working

**Comment by JamesPHoughton** [comment]
Yeah, it was correct for me too. A hard one to replicate. Let’s just try it
in all the browsers, and resize the screen a bunch and see what we can do.

**Comment by gumillie222** [comment]
I've tested in chrome, safari, and firefox, and in different sizes too, they are all currently working on my laptop.

**Comment by JamesPHoughton** [comment]
cool, lets call this done then
