### ISSUE TITLE
Create a "partners" tab

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-website#14]
Create a new page called "partners", and in it, list each of the groups we are working with. Should be divided into two sections for "Researchers" and "Sponsors". Move the university logos to the "researchers" section by themselves for now, we'll need to add some text later.

**Comment by JamesPHoughton** [comment]
Researchers:
1. University of Pennsylvania: Computational Social Science Lab (https://css.seas.upenn.edu/)
    - James Houghton (https://www.jamesphoughton.com/)
    - Duncan Watts (https://css.seas.upenn.edu/people/duncan-watts/)
    - Emily Hu (https://xinlanemilyhu.com/)

2. University of Pennsylvania: Wharton School (https://www.wharton.upenn.edu/)
    - Dean Knox (https://oid.wharton.upenn.edu/profile/dcknox/)
  
3. University of Reading: School of Psychology and Clinical Language Sciences (https://www.reading.ac.uk/pcls/) 
    - Netta Weinstein (https://www.reading.ac.uk/pcls/staff/netta-weinstein)
    
4. Princeton University: Department of Politics (https://politics.princeton.edu/)
    - Will Schulz (https://willschulz.com/)

5. Washington University in St. Louis: Department of Political Science (https://polisci.wustl.edu/)
    - Christopher Lucas (http://christopherlucas.org/)

Sponsors:
1. Templeton World Charity Foundation, Listening and Learning in a Polarized World (https://www.templetonworldcharity.org/LLPW)
     - We have the logo in white in the img folder, but may need to find one appropriate for a light background.

2. Wharton Behavioral Lab (https://wbl.wharton.upenn.edu/)
    - (don't have a logo yet)

**Comment by gumillie222** [comment]
For researchers, do we want it to look like a list? Or do we want to make it like the css lab website, with image and name & affiliation under?

**Comment by JamesPHoughton** [comment]
Lets get the logo for each school, but under that it can just be a list. I hope that eventually this will be quite a long list. =) Beyond that, I'll defer to your aesthetic judgement
